import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
	return (
		<>
			<Head>
				<title>Home | FrancesCode</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='bg-white'>
				// Write a dummy content for the home page
				<div>
					<h1 className='text-4xl font-bold'>Home</h1>
					<p className='text-gray-500'>
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam,
						quod.
					</p>

					<div className='flex flex-col items-center justify-center min-h-screen py-2'>
						<Image
							src='/images/nextjs.svg'
							width={200}
							height={200}
							alt='NextJS Logo'
						/>
						<Image
							src='/images/tailwindcss.svg'
							width={200}
							height={200}
							alt='TailwindCSS Logo'
						/>

						<p className='mt-4 text-2xl font-bold'>
							Welcome to{' '}
							<a className='text-blue-600' href='https://nextjs.org'>
								FrancesCode
							</a>
						</p>
					</div>
				</div>
			</main>
		</>
	)
}
